### ISSUE TITLE
Add load() and unload() methods to BasePerson

### ISSUE THREAD

**Issue by Stemist** [pachocanadian/sole#13]
BaseElevator calls its own unload(self) method

def unload(self):
        carrying = self.get("carrying")
        if(type(carrying) == list):
            for p in carrying:
                p.unload()

It looks like BasePerson will need its own load() and unload() methods as "p.unload()" is calling a method belonging to a person object in the carrying list that doesn't exist.

**Comment by Stemist** [comment]
I was wondering if it makes slightly more intuitive sense for the elevator to "unload" itself rather than a person to unload themselves.

**Comment by pachocanadian** [comment]
If so then it's the same argument with floors.

If an elevator unloads, are they then inspecting each person to see who
gets unloaded?

I don't really care either way, put some functional code in place and we'll
see how it pans out.
