### ISSUE TITLE
Project file permissions

### ISSUE THREAD

**Issue by Stemist** [pachocanadian/sole#2]
On a fresh Fedora 30 install I git cloned the sole repo but am finding after setting up Vim with Black that I am unable to edit project files as they appear read-only to my system. Could this be a problem on my end?

**Comment by pachocanadian** [comment]
Compare the output of "ls -l" with "id". Are the files owned by the user
that you're running as? I believe you checked out the files as root and
then are trying to edit them as a normal user.
--
Mike Carr, DTM

**Comment by Stemist** [comment]
Ah, thanks to your emails I realised what happened.

When I set up my clones I did it using a setup script that I ran with sudo which set the cloned file permissions as root. The script mixed update and upgrade commands with git clones. I should move the git cloning to another script to run as normal user to avoid that happening.

Good security advice. The files being setup as root permission confused me as I'm aware of avoiding root use, until I remembered my script.

Thanks for spotting it! :)

Christian Pearson
