### ISSUE TITLE
Define and document real-world defaults for standard operations

### ISSUE THREAD

**Issue by pachocanadian** [pachocanadian/sole#26]
Identify and document the following defaults in real world seconds:
- How long does it take for an elevator to travel between floors? Infer a rough velocity in m/s.
- How long does it take for elevator doors to open? To close?
- How long does an elevator wait with doors open before proceeding?
- How long does an elevator delay before going into motion once doors are closed?
- Roughly how long does it take an able bodied individual to enter or depart an elevator?

**Comment by Stemist** [comment]
Added page: https://github.com/pachocanadian/sole/wiki/Time-Constraints

**Comment by pachocanadian** [comment]
Very good!

Strike the internal acceleration part.
Put your acceleration in m/s^2 units
Reformat into a table - three columns - descriptive name, variable name in snake_case, constant
Add "door close time" which would be the same as "door open time"

**Comment by Stemist** [comment]
Changes made. Will adjust for actual variables used in code.
