### ISSUE TITLE
Sketch out different suite types

### ISSUE THREAD

**Issue by pachocanadian** [pachocanadian/sole#29]
- e.g. residence, business
- can these span multiple floors or confined to a single floor?
- can multiple exist on a given floor?
- can these be locators for creation of people?
- can these allow for different times of day for people to be created?
- this is all for long term GUI support and to make the building more reasonable in its operation

**Comment by Stemist** [comment]
Created Wiki page: https://github.com/pachocanadian/sole/wiki/Building-Floor-and-Suite-types

**Comment by pachocanadian** [comment]
brilliant, not what I envisioned, but definitely meets the mark
