### ISSUE TITLE
Define potential narrative constructs, e.g. don't code, just write out ideas

### ISSUE THREAD

**Issue by pachocanadian** [pachocanadian/sole#30]
e.g. Person frustrated with wait times, being late to work
e.g. Person talking about sports team
e.g. Person talking about favorite superhero

**Comment by Stemist** [comment]
Created Wiki page: https://github.com/pachocanadian/sole/wiki/Person-Internal-Monologue-Samples

**Comment by pachocanadian** [comment]
good! I didn't envision the personality types but otherwise exactly the right idea
